#!/bin/bash
# Author: Nasir
# Date: 29-07-2024 | Modified Date: 29-07-2024
# Description: To check disk space
  
a=`df -h | awk '{print $5}' | cut -d'%' -f1
for i in $a
do
if [ $i -ge 20 ]
then
echo "The disk space is more than 20% for below for systems"
echo `df -h | grep $i`
fi
done
