#!/bin/bash

# NOTE:
# 1. Jenkins works on port 8080, so keep the port open while creating EC2 instance
# 2. Jenkins requires Java & supports versions 11,17 & 21

# ------------------
# INSTALL JAVA 17
# ------------------
# REF: https://www.rosehosting.com/blog/how-to-install-java-17-lts-on-ubuntu-20-04/
sudo apt update -y
sudo apt install openjdk-17-jdk openjdk-17-jre -y
java -version

# ------------------
# INSTALL JENKINS
# ------------------
# REF: https://www.jenkins.io/doc/book/installing/linux/#debianubuntu

sudo wget -O /usr/share/keyrings/jenkins-keyring.asc https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
echo "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc]" https://pkg.jenkins.io/debian-stable binary/ | sudo tee /etc/apt/sources.list.d/jenkins.list > /dev/null

sudo apt update                                      # to update package
sudo apt install jenkins -y                          # to install jenkins

sudo systemctl status jenkins                        # to check the status if jenkins is running or not

# Get Jenkins_Public_IP
ip=$(curl ifconfig.me)
port=8080

# Generate Jenkins initial login password
pass=$(sudo cat /var/lib/jenkins/secrets/initialAdminPassword)

echo "Access your Jenkins here --> http://$ip:$port"
echo "Your Jenkins Initial Password: $pass"
