#!/bin/bash
# NOTE:
# 1. Jenkins works on port 8080, so keep the port open while creating EC2 instance
# 2. Jenkins also requires Java & supports versions 11,17 & 21

# ------------------
# INSTALL JAVA17
# ------------------
# Ref: https://stackoverflow.com/questions/69243384/how-do-i-install-jdk-17-on-my-aws-ami-ec2-instance
# Ref: https://www.oracle.com/java/technologies/javase/jdk17-archive-downloads.html

wget https://download.oracle.com/java/17/archive/jdk-17.0.12_linux-x64_bin.tar.gz
sudo mkdir -p /usr/lib/jvm
cd /usr/lib/jvm
sudo tar -xvzf jdk-17.0.12_linux-x64_bin.tar.gz
sudo ${EDITOR} /etc/environment
# Add this to the $PATH variable
/usr/lib/jvm/jdk-17/bin
JAVA_HOME="/usr/lib/jvm/jdk-17"

sudo update-alternatives --install "/usr/bin/java" "java" "/usr/lib/jvm/jdk-17/bin/java" 0
sudo update-alternatives --install "/usr/bin/javac" "javac" "/usr/lib/jvm/jdk-17/bin/javac" 0
sudo update-alternatives --set java /usr/lib/jvm/jdk-17/bin/java
sudo update-alternatives --set javac /usr/lib/jvm/jdk-17/bin/javac

java -version

# ------------------
# INSTALL DOCKER
# ------------------
# REF: (https://www.jenkins.io/doc/tutorials/tutorial-for-installing-jenkins-on-AWS/)
sudo yum update -y
sudo wget -O /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat-stable/jenkins.repo
sudo rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
sudo yum install java-17-amazon-corretto -y
sudo yum install jenkins -y
sudo systemctl enable jenkins
sudo systemctl start jenkins

# Get Jenkins_Public_IP
ip=$(curl ifconfig.me)
port=8080

# Generate Jenkins initial login password
pass=$(sudo cat /var/lib/jenkins/secrets/initialAdminPassword)

echo "Access your Jenkins here --> http://$ip:$port"
echo "Your Jenkins Initial Password: $pass"

# In case if Jenkins fails to starts, try to set Java version to 11,17,21 using below command
# sudo /usr/sbin/alternatives --config java 
# (Select the relevant Java version: 11,17 or 21)
