#!/bin/bash
# Author: Nasir
# Date: 29-07-2024 | Modified Date: 29-07-2024
# Description: To give execute permissions to files w/ names Server1 - 10

for i in Server*
  do
    chmod a+x $i 
    sleep 1
done
