#!/bin/bash
# Author: Nasir
# Date: 29-07-2024 | Modified Date: 29-07-2024
# Description: To check if a file exists in the location
  
if [ -e /home/user/error.txt ]
then
echo "File exists"
else
echo "File doesn't exists!"
fi
